[Server Settings]
SERVER_IP=127.0.0.1
SERVER_PORT=8000

[Client Settings]
WORDLIST_FILE=D:\GitHub\Distributed-Hash-Cracker-CPP\x64\Debug\wordlist.txt

# Show progress of cracking which prints each attempt in client console.
SHOW_PROGRESS=TRUE

AUTO_RECONNECT=TRUE

# If mutator rules list is empty, mutation are disabled.
# However, if it is enabled, it will attempt to mutate
# each word depending on the rule.

# l = lowercase
# u = uppercase
# r = reverse
# c = capitalize first letter
# t = toggle case
# d = duplicate
# s = substitute sXY
# n = append numbers
# 3 = l33tsp3@k

MUTATION_RULES=l, u, r, c, t, d, s, n, 3