[Server Settings]
SERVER_IP=127.0.0.1
SERVER_PORT=8000

[Client Settings]
WORDLIST_FILE=D:\GitHub\Distributed-Hash-Cracker-CPP\x64\Debug\wordlist.txt

# Show progress of cracking which prints each attempt in client console.
SHOW_PROGRESS=TRUE

AUTO_RECONNECT=TRUE