[Server Settings]
SERVER_IP=127.0.0.1
SERVER_PORT=8000

[Client Settings]
WORDLIST_FILE=D:\GitHub\Distributed-Hash-Cracker-CPP\x64\Debug\wordlist.txt

# Line count of wordlist file (optional)
# If set to AUTO, it will automatically count the line count on client initialization/reload.
# This only takes effect when MULTI_THREADING is enabled below.
LINE_COUNT=AUTO

# Show progress of cracking which prints each attempt in client console.
SHOW_PROGRESS=TRUE

# Auto reconnects to server indefinitely until client is shut down.
AUTO_RECONNECT=TRUE

# Multi-threaded (parallel processing) when enabled, single-threaded when disabled.
# Multi-threaded performance is slower (at startup/initialization) in larger wordlist
# files as it needs to count the entire file lines count as the client initializes or
# every time it reloads to distribute the workload properly on all threads.

# Single threaded cracking has a faster startup/initialization time as it does
# not require to count the lines at the beginning of running the client.

# Choose depending on the wordlist file size.
MULTI_THREADED=FALSE